<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260120132958 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX idx_invoice_due_date');
        $this->addSql('DROP INDEX idx_invoice_status');
        $this->addSql('ALTER TABLE invoice ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE invoice ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE invoice ALTER total_hours DROP DEFAULT');
        $this->addSql('ALTER TABLE invoice ALTER hourly_rate DROP DEFAULT');
        $this->addSql('ALTER TABLE invoice ALTER subtotal DROP DEFAULT');
        $this->addSql('ALTER TABLE invoice ALTER tax_rate DROP DEFAULT');
        $this->addSql('ALTER TABLE invoice ALTER tax_amount DROP DEFAULT');
        $this->addSql('ALTER TABLE invoice ALTER total DROP DEFAULT');
        $this->addSql('ALTER TABLE invoice ALTER status DROP DEFAULT');
        $this->addSql('ALTER INDEX invoice_invoice_number_key RENAME TO UNIQ_906517442DA68207');
        $this->addSql('ALTER INDEX idx_invoice_domicile_id RENAME TO IDX_9065174495715F7D');
        $this->addSql('ALTER INDEX idx_invoice_executor_id RENAME TO IDX_906517448ABD09BB');
        $this->addSql('DROP INDEX idx_task_time_log_status');
        $this->addSql('ALTER TABLE task_time_log ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE task_time_log ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE task_time_log ALTER hours_worked DROP DEFAULT');
        $this->addSql('ALTER TABLE task_time_log ALTER status DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_task_time_log_task_id RENAME TO IDX_157EE9E38DB60186');
        $this->addSql('ALTER INDEX idx_task_time_log_executor_id RENAME TO IDX_157EE9E38ABD09BB');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE invoice ALTER id SET DEFAULT nextval(\'invoice_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE invoice ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE invoice ALTER total_hours SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE invoice ALTER hourly_rate SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE invoice ALTER subtotal SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE invoice ALTER tax_rate SET DEFAULT \'20.0\'');
        $this->addSql('ALTER TABLE invoice ALTER tax_amount SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE invoice ALTER total SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE invoice ALTER status SET DEFAULT \'DRAFT\'');
        $this->addSql('CREATE INDEX idx_invoice_due_date ON invoice (due_date)');
        $this->addSql('CREATE INDEX idx_invoice_status ON invoice (status)');
        $this->addSql('ALTER INDEX uniq_906517442da68207 RENAME TO invoice_invoice_number_key');
        $this->addSql('ALTER INDEX idx_9065174495715f7d RENAME TO idx_invoice_domicile_id');
        $this->addSql('ALTER INDEX idx_906517448abd09bb RENAME TO idx_invoice_executor_id');
        $this->addSql('ALTER TABLE task_time_log ALTER id SET DEFAULT nextval(\'task_time_log_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE task_time_log ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE task_time_log ALTER hours_worked SET DEFAULT \'0\'');
        $this->addSql('ALTER TABLE task_time_log ALTER status SET DEFAULT \'PENDING\'');
        $this->addSql('CREATE INDEX idx_task_time_log_status ON task_time_log (status)');
        $this->addSql('ALTER INDEX idx_157ee9e38abd09bb RENAME TO idx_task_time_log_executor_id');
        $this->addSql('ALTER INDEX idx_157ee9e38db60186 RENAME TO idx_task_time_log_task_id');
    }
}
