<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260218130705 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE activity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AC74095AA76ED395 ON activity (user_id)');
        $this->addSql('CREATE TABLE badge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) NOT NULL, icon VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE content (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(100) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE favorite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, label VARCHAR(255) NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_68C58ED9A76ED395 ON favorite (user_id)');
        $this->addSql('CREATE TABLE log_entry (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(100) NOT NULL, message VARCHAR(255) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE notification (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, message TEXT NOT NULL, read BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BF5476CAA76ED395 ON notification (user_id)');
        $this->addSql('CREATE TABLE support_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, subject VARCHAR(255) DEFAULT NULL, message TEXT NOT NULL, status VARCHAR(20) DEFAULT \'open\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE user_settings (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, theme VARCHAR(10) NOT NULL, lang VARCHAR(5) NOT NULL, notifications BOOLEAN NOT NULL, twofa BOOLEAN NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5C844C5A76ED395 ON user_settings (user_id)');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE favorite ADD CONSTRAINT FK_68C58ED9A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_settings ADD CONSTRAINT FK_5C844C5A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('DROP INDEX idx_pending_email_created');
        $this->addSql('DROP INDEX idx_pending_email_status');
        $this->addSql('ALTER TABLE pending_email ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE pending_email ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE pending_email ALTER created_at DROP DEFAULT');
        $this->addSql('ALTER TABLE pending_email ALTER failure_reason TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE pending_email ALTER retry_count DROP DEFAULT');
        $this->addSql('ALTER TABLE refresh_token ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE refresh_token ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX refresh_token_token_key RENAME TO UNIQ_C74F21955F37A13B');
        $this->addSql('ALTER TABLE "user" ADD created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE activity DROP CONSTRAINT FK_AC74095AA76ED395');
        $this->addSql('ALTER TABLE favorite DROP CONSTRAINT FK_68C58ED9A76ED395');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE user_settings DROP CONSTRAINT FK_5C844C5A76ED395');
        $this->addSql('DROP TABLE activity');
        $this->addSql('DROP TABLE badge');
        $this->addSql('DROP TABLE content');
        $this->addSql('DROP TABLE favorite');
        $this->addSql('DROP TABLE log_entry');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE support_message');
        $this->addSql('DROP TABLE user_settings');
        $this->addSql('ALTER TABLE pending_email ALTER id SET DEFAULT nextval(\'pending_email_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE pending_email ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE pending_email ALTER created_at SET DEFAULT \'now()\'');
        $this->addSql('ALTER TABLE pending_email ALTER failure_reason TYPE TEXT');
        $this->addSql('ALTER TABLE pending_email ALTER retry_count SET DEFAULT 0');
        $this->addSql('CREATE INDEX idx_pending_email_created ON pending_email (created_at)');
        $this->addSql('CREATE INDEX idx_pending_email_status ON pending_email (sent_at, failure_reason)');
        $this->addSql('ALTER TABLE refresh_token ALTER id SET DEFAULT nextval(\'refresh_token_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE refresh_token ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX uniq_c74f21955f37a13b RENAME TO refresh_token_token_key');
        $this->addSql('ALTER TABLE "user" DROP created_at');
        $this->addSql('ALTER TABLE "user" DROP updated_at');
    }
}
