<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260219100534 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // Migration dupliquée de Version20260219100526 — skip si tables existent déjà
        $this->addSql("DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'monthly_budget') THEN
                CREATE TABLE monthly_budget (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, year INT NOT NULL, month INT NOT NULL, budget_amount DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, domicile_id INT NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id));
                CREATE INDEX IDX_905264B095715F7D ON monthly_budget (domicile_id);
                CREATE INDEX IDX_905264B0B03A8386 ON monthly_budget (created_by_id);
                CREATE UNIQUE INDEX unique_budget_month ON monthly_budget (domicile_id, year, month);
                ALTER TABLE monthly_budget ADD CONSTRAINT FK_905264B095715F7D FOREIGN KEY (domicile_id) REFERENCES domicile (id) ON DELETE CASCADE NOT DEFERRABLE;
                ALTER TABLE monthly_budget ADD CONSTRAINT FK_905264B0B03A8386 FOREIGN KEY (created_by_id) REFERENCES \"user\" (id) NOT DEFERRABLE;
            END IF;
        END $$;");
        $this->addSql("DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'recurring_task_template') THEN
                CREATE TABLE recurring_task_template (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, frequency VARCHAR(20) NOT NULL, days_of_week VARCHAR(50) DEFAULT NULL, preferred_start_time VARCHAR(5) DEFAULT NULL, estimated_duration_minutes INT DEFAULT NULL, start_date DATE NOT NULL, end_date DATE DEFAULT NULL, is_active BOOLEAN NOT NULL, last_generated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, domicile_id INT NOT NULL, assigned_to_id INT NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id));
                CREATE INDEX IDX_D76E354C95715F7D ON recurring_task_template (domicile_id);
                CREATE INDEX IDX_D76E354CF4BD7827 ON recurring_task_template (assigned_to_id);
                CREATE INDEX IDX_D76E354CB03A8386 ON recurring_task_template (created_by_id);
                ALTER TABLE recurring_task_template ADD CONSTRAINT FK_D76E354C95715F7D FOREIGN KEY (domicile_id) REFERENCES domicile (id) ON DELETE CASCADE NOT DEFERRABLE;
                ALTER TABLE recurring_task_template ADD CONSTRAINT FK_D76E354CF4BD7827 FOREIGN KEY (assigned_to_id) REFERENCES \"user\" (id) NOT DEFERRABLE;
                ALTER TABLE recurring_task_template ADD CONSTRAINT FK_D76E354CB03A8386 FOREIGN KEY (created_by_id) REFERENCES \"user\" (id) NOT DEFERRABLE;
            END IF;
        END $$;");
        $this->addSql("DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'public' AND table_name = 'task_review') THEN
                CREATE TABLE task_review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, rating INT NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, task_id INT NOT NULL, reviewed_by_id INT NOT NULL, executor_id INT NOT NULL, PRIMARY KEY (id));
                CREATE UNIQUE INDEX UNIQ_42EA05158DB60186 ON task_review (task_id);
                CREATE INDEX IDX_42EA0515FC6B21F1 ON task_review (reviewed_by_id);
                CREATE INDEX IDX_42EA05158ABD09BB ON task_review (executor_id);
                ALTER TABLE task_review ADD CONSTRAINT FK_42EA05158DB60186 FOREIGN KEY (task_id) REFERENCES task (id) ON DELETE CASCADE NOT DEFERRABLE;
                ALTER TABLE task_review ADD CONSTRAINT FK_42EA0515FC6B21F1 FOREIGN KEY (reviewed_by_id) REFERENCES \"user\" (id) NOT DEFERRABLE;
                ALTER TABLE task_review ADD CONSTRAINT FK_42EA05158ABD09BB FOREIGN KEY (executor_id) REFERENCES \"user\" (id) NOT DEFERRABLE;
            END IF;
        END $$;");
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE monthly_budget DROP CONSTRAINT FK_905264B095715F7D');
        $this->addSql('ALTER TABLE monthly_budget DROP CONSTRAINT FK_905264B0B03A8386');
        $this->addSql('ALTER TABLE recurring_task_template DROP CONSTRAINT FK_D76E354C95715F7D');
        $this->addSql('ALTER TABLE recurring_task_template DROP CONSTRAINT FK_D76E354CF4BD7827');
        $this->addSql('ALTER TABLE recurring_task_template DROP CONSTRAINT FK_D76E354CB03A8386');
        $this->addSql('ALTER TABLE task_review DROP CONSTRAINT FK_42EA05158DB60186');
        $this->addSql('ALTER TABLE task_review DROP CONSTRAINT FK_42EA0515FC6B21F1');
        $this->addSql('ALTER TABLE task_review DROP CONSTRAINT FK_42EA05158ABD09BB');
        $this->addSql('DROP TABLE monthly_budget');
        $this->addSql('DROP TABLE recurring_task_template');
        $this->addSql('DROP TABLE task_review');
    }
}
