<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260113132016 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE domicile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, address VARCHAR(500) DEFAULT NULL, phone VARCHAR(20) DEFAULT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F6305DA2B03A8386 ON domicile (created_by_id)');
        $this->addSql('CREATE TABLE domicile_executor (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, domicile_id INT NOT NULL, executor_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B66BDD9F95715F7D ON domicile_executor (domicile_id)');
        $this->addSql('CREATE INDEX IDX_B66BDD9F8ABD09BB ON domicile_executor (executor_id)');
        $this->addSql('CREATE TABLE task (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, status VARCHAR(50) NOT NULL, start_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, end_time TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, assigned_to_id INT DEFAULT NULL, domicile_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_527EDB25F4BD7827 ON task (assigned_to_id)');
        $this->addSql('CREATE INDEX IDX_527EDB2595715F7D ON task (domicile_id)');
        $this->addSql('CREATE TABLE task_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action INT NOT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, task_id INT DEFAULT NULL, executor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_385B5AA18DB60186 ON task_history (task_id)');
        $this->addSql('CREATE INDEX IDX_385B5AA18ABD09BB ON task_history (executor_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, role VARCHAR(50) NOT NULL, password VARCHAR(255) NOT NULL, first_name VARCHAR(100) DEFAULT NULL, last_name VARCHAR(100) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0 ON messenger_messages (queue_name)');
        $this->addSql('CREATE INDEX IDX_75EA56E0E3BD61CE ON messenger_messages (available_at)');
        $this->addSql('CREATE INDEX IDX_75EA56E016BA31DB ON messenger_messages (delivered_at)');
        $this->addSql('ALTER TABLE domicile ADD CONSTRAINT FK_F6305DA2B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE domicile_executor ADD CONSTRAINT FK_B66BDD9F95715F7D FOREIGN KEY (domicile_id) REFERENCES domicile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE domicile_executor ADD CONSTRAINT FK_B66BDD9F8ABD09BB FOREIGN KEY (executor_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25F4BD7827 FOREIGN KEY (assigned_to_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB2595715F7D FOREIGN KEY (domicile_id) REFERENCES domicile (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE task_history ADD CONSTRAINT FK_385B5AA18DB60186 FOREIGN KEY (task_id) REFERENCES task (id)');
        $this->addSql('ALTER TABLE task_history ADD CONSTRAINT FK_385B5AA18ABD09BB FOREIGN KEY (executor_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE domicile DROP CONSTRAINT FK_F6305DA2B03A8386');
        $this->addSql('ALTER TABLE domicile_executor DROP CONSTRAINT FK_B66BDD9F95715F7D');
        $this->addSql('ALTER TABLE domicile_executor DROP CONSTRAINT FK_B66BDD9F8ABD09BB');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB25F4BD7827');
        $this->addSql('ALTER TABLE task DROP CONSTRAINT FK_527EDB2595715F7D');
        $this->addSql('ALTER TABLE task_history DROP CONSTRAINT FK_385B5AA18DB60186');
        $this->addSql('ALTER TABLE task_history DROP CONSTRAINT FK_385B5AA18ABD09BB');
        $this->addSql('DROP TABLE domicile');
        $this->addSql('DROP TABLE domicile_executor');
        $this->addSql('DROP TABLE task');
        $this->addSql('DROP TABLE task_history');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
