export const defaultConfig = Object.freeze({
  app_name: 'Homi',
  tagline: 'Manage your home tasks efficiently',
  welcome_message: 'Welcome back',
  login_button_text: 'Sign in to your account',
  forgot_password_text: 'Forgot your password?',
  signup_text: "Don't have an account?",
  signup_link_text: 'Sign up',
  font_family: 'Inter',
  search_placeholder: 'Search...',
  nav_dashboard: 'Dashboard',
  nav_tasks: 'Tasks',
  nav_executors: 'Executors',
  nav_messages: 'Messages',
  nav_analytics: 'Analytics',
  nav_settings: 'Settings',
  profile_view: 'View Profile',
  profile_preferences: 'Preferences',
  profile_logout: 'Logout',
  font_size: 16
});
